APPLICATION_NAME = Updater
APP_ID = jp.ashikase.backgrounder

Updater_BUNDLE_NAME = Backgrounder
Updater_OBJC_FILES = main.m
Updater_CFLAGS = -std=gnu99 -DAPP_ID=\"$(APP_ID)\"
Updater_PRIVATE_FRAMEWORKS = SpringBoardServices

include ../framework/makefiles/common.mk
include ../framework/makefiles/application.mk
